version: "3.8"

services:
  app:
    depends_on:
      - server
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network



networks:
  app-network:
    driver: bridge